import type { Ticket } from "./types";

// Dados realistas de uma marcenaria/rede varejista brasileira
export const TICKETS_MOCK: Ticket[] = [
  {
    id: "FVF-2025-0142",
    cliente: "Residência Alphaville — Família Tavares",
    cidade: "Barueri / SP",
    danfe: "NF-e 45213",
    lote: "L-FAB-09-2025-B12",
    status: "ABERTO",
    responsabilidade: "TRANSPORTE",
    severidade: "ALTA",
    scores: { transporte: 78, fabrica: 14, montagem: 8 },
    pecas: [
      {
        id: "p1",
        descricao: "Porta de correr 1800x2400mm",
        material: "MDF Ultra 18mm — Carvalho Hanover",
        evidencia: 3,
        score: 82,
      },
      {
        id: "p2",
        descricao: "Fita de borda superior descolada",
        material: "PVC 2mm — ref. 8710",
        evidencia: 1,
        score: 41,
      },
    ],
    abertoEm: "2025-10-14T08:21:00Z",
    slaHoras: 6,
    responsavel: undefined,
  },
  {
    id: "FVF-2025-0139",
    cliente: "Loja Concept Móveis — Showroom Vila Olímpia",
    cidade: "São Paulo / SP",
    danfe: "NF-e 45198",
    lote: "L-FAB-09-2025-A07",
    status: "ABERTO",
    responsabilidade: "FABRICA",
    severidade: "CRITICA",
    scores: { transporte: 12, fabrica: 84, montagem: 4 },
    pecas: [
      {
        id: "p1",
        descricao: "Prateleira curva 600x300mm",
        material: "MDF Branco TX 15mm",
        evidencia: 2,
        score: 91,
      },
    ],
    abertoEm: "2025-10-14T06:02:00Z",
    slaHoras: 2,
  },
  {
    id: "FVF-2025-0137",
    cliente: "Residência Praia Grande — Sr. Almeida",
    cidade: "Praia Grande / SP",
    danfe: "NF-e 45182",
    lote: "L-FAB-08-2025-D22",
    status: "TRIAGEM",
    responsabilidade: "MONTAGEM",
    severidade: "MEDIA",
    scores: { transporte: 9, fabrica: 11, montagem: 80 },
    pecas: [
      {
        id: "p1",
        descricao: "Painel ripado 2500x1200mm",
        material: "MDF Freijó 25mm",
        evidencia: 4,
        score: 73,
      },
      {
        id: "p2",
        descricao: "Dobradiça caneco 35mm (desregulagem)",
        material: "Aço inox — ref. H35-SOFT",
        evidencia: 2,
        score: 58,
      },
    ],
    abertoEm: "2025-10-13T14:48:00Z",
    slaHoras: 18,
    responsavel: "Ana Beatriz (Triagem)",
  },
  {
    id: "FVF-2025-0133",
    cliente: "Escritório Coworking Berrini",
    cidade: "São Paulo / SP",
    danfe: "NF-e 45144",
    lote: "L-FAB-08-2025-C04",
    status: "TRIAGEM",
    responsabilidade: "TRANSPORTE",
    severidade: "BAIXA",
    scores: { transporte: 64, fabrica: 22, montagem: 14 },
    pecas: [
      {
        id: "p1",
        descricao: "Arranhões na superfície — Mesa diretoria",
        material: "Laca acetinada preta",
        evidencia: 5,
        score: 66,
      },
    ],
    abertoEm: "2025-10-13T11:10:00Z",
    slaHoras: 24,
    responsavel: "Carlos Drumond (Triagem)",
  },
  {
    id: "FVF-2025-0128",
    cliente: "Residência Moema — Família Rocha",
    cidade: "São Paulo / SP",
    danfe: "NF-e 45099",
    lote: "L-FAB-08-2025-B18",
    status: "EM_ANALISE",
    responsabilidade: "FABRICA",
    severidade: "ALTA",
    scores: { transporte: 18, fabrica: 71, montagem: 11 },
    pecas: [
      {
        id: "p1",
        descricao: "Trilho superior deslizante travando",
        material: "Alumínio anodizado",
        evidencia: 2,
        score: 88,
      },
    ],
    abertoEm: "2025-10-12T09:30:00Z",
    slaHoras: 36,
    responsavel: "Fornecedor: Ind. Móveis Hannover",
  },
  {
    id: "FVF-2025-0119",
    cliente: "Residência Pinheiros — Sr. Vasconcelos",
    cidade: "São Paulo / SP",
    danfe: "NF-e 45021",
    lote: "L-FAB-07-2025-A31",
    status: "EM_ANALISE",
    responsabilidade: "MONTAGEM",
    severidade: "MEDIA",
    scores: { transporte: 6, fabrica: 9, montagem: 85 },
    pecas: [
      {
        id: "p1",
        descricao: "Parafuso minifix solto (gaveteiro)",
        material: "Aço zamak M6",
        evidencia: 1,
        score: 79,
      },
    ],
    abertoEm: "2025-10-11T15:25:00Z",
    slaHoras: 48,
    responsavel: "Equipe Montagem SP-2",
  },
  {
    id: "FVF-2025-0105",
    cliente: "Residência Tatuapé — Sra. Marques",
    cidade: "São Paulo / SP",
    danfe: "NF-e 44872",
    lote: "L-FAB-07-2025-C09",
    status: "RESOLVIDO",
    responsabilidade: "TRANSPORTE",
    severidade: "BAIXA",
    scores: { transporte: 88, fabrica: 7, montagem: 5 },
    pecas: [
      {
        id: "p1",
        descricao: "Canto inferior esmagado",
        material: "MDF Branco 15mm",
        evidencia: 3,
        score: 92,
      },
    ],
    abertoEm: "2025-10-09T10:00:00Z",
    slaHoras: 0,
    responsavel: "Logística Rota 04",
  },
  {
    id: "FVF-2025-0098",
    cliente: "Loja Decore+ — Shopping Iguatemi",
    cidade: "Campinas / SP",
    danfe: "NF-e 44811",
    lote: "L-FAB-06-2025-E02",
    status: "RESOLVIDO",
    responsabilidade: "FABRICA",
    severidade: "MEDIA",
    scores: { transporte: 8, fabrica: 81, montagem: 11 },
    pecas: [
      {
        id: "p1",
        descricao: "Fita de borda soltando — lateral esquerda",
        material: "PVC 0.4mm — ref. 2104",
        evidencia: 2,
        score: 70,
      },
    ],
    abertoEm: "2025-10-07T08:40:00Z",
    slaHoras: 0,
    responsavel: "Reposição enviada",
  },
];
